FROM node:16-alpine
WORKDIR '/app'
COPY ./package.json ./
# prevent React bug ESLint missing mkdir rights
RUN mkdir -p /app/node_modules
RUN chown node:node /app/node_modules

RUN npm install
COPY . .
CMD ["npm", "run", "start"]